[build]
  functions = "functions"
  publish = "out"

[functions]
  node_bundler = "esbuild"

[dev]
  publish = "out"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
